# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 76c73a7
_src_path: /home/rochacbruno/Projects/platform-service-framework
project_name: platform_service_example
src_branch: main
template: templates/project
