# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 877b1e9
_src_path: https://github.com/ansible/platform-service-framework.git
app_name: ''
apps:
- core
- api
project_name: platform_service_example
src_branch: 877b1e98b8ce4cad5a593eb93ccde3d5544e6a67
template: templates/project
