# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1e47ae3
_src_path: https://github.com/ansible/platform-service-framework.git
app_name: ''
apps:
- core
- api
project_name: platform_service_example
src_branch: 1e47ae3edd33fe332e1a0ae80366c59b6dd08d7c
template: templates/project
