# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1b4ee95
_src_path: https://github.com/ansible/platform-service-framework.git
app_name: ''
apps:
- core
- api
project_name: platform_service_example
src_branch: feat/check-ci
template: templates/project
