# WARNING: DO NOT EDIT THIS FILE, IT IS MANAGED BY ANSIBLE-SERVICES-FRAMEWORK.
"""
URL configuration for project project.

This file is managed by the Ansible Services Framework

## Loading order

1. Load the base URL patterns (inclusing DAB)
2. Load the URL patterns for each app
3. Load the debug and development URLS

"""

import importlib

from django.conf import settings
from django.urls import include, path

urlpatterns = []

# TODO (rochacbruno):  Load DAB URLs dynamically here.

# Extend URL patterns for each app
for app in settings.LOADED_APPS:
    app_name = app.split(".")[-1]
    url_module_path = f"{app}.urls"
    urls = importlib.import_module(url_module_path)
    if patterns := getattr(urls, "urlpatterns", None):
        urlpatterns.append(path(f"{app_name}/", include(url_module_path)))

# Debug and Development URLS
if not settings.DYNACONF.get("IS_RUNNING_TESTS") and settings.DYNACONF.get("DEBUG"):
    from debug_toolbar.toolbar import debug_toolbar_urls  # noqa

    urlpatterns.extend(debug_toolbar_urls())
