# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: a1e4458
_src_path: https://github.com/ansible/platform-service-framework.git
app_name: core
apps:
- core
- api
project_name: platform_service_example
src_branch: 4dbc570f3a80fe0619aeed55379341a4f41a499c
template: templates/core
